int five();
const char * five_roman();
const char * five_morsecode();
int five_negative();
const char * five_loud();
const char * five_english();
const char * five_irish();
int five_binary();
int five_octal();
int five_hex();
